### ISSUE TITLE
Create Endpoint - Delete

### ISSUE THREAD

**Issue by gschadegg** [webdev-20/TLL-hacktoberfest-2022#13]
**Task**
What is the task?
Create (backend) endpoint to delete previously shortened URLs

**More about the task (optional)**

**Alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by MaestroDagan** [comment]
I'm going to start working on this issue rn!

**Comment by cherylli** [comment]
> I'm going to start working on this issue rn!

no you cannot. This issue has already been assigned to @gschadegg 
Please find an unassigned issue or task to work on

**Comment by MaestroDagan** [comment]
oh, i thought that she was assigned because she opened it. Sorry, ill search for an unassigned one

**Comment by cherylli** [comment]
pr #51
