### ISSUE TITLE
Add how to pull latest changes to local branch to contributing.md

### ISSUE THREAD

**Issue by cherylli** [webdev-20/TLL-hacktoberfest-2022#22]
**Task**
Add a section to contributing on how to pull latest changes, which should be done before every PR

**More about the task**

This should work
1. fetch from upstream 
`git fetch upstream`	

2. pull upstream/main into current branch
(on local branch) `git merge upstream/main`
resolve conflicts if needed

**Additional context (optional)**
Preferrably after you have tested the above workflow, or familiar with the process

**Comment by praveen-221** [comment]
I would like to work on this issue under hacktoberfest 2022
