### ISSUE TITLE
feat: custom short link (back-end)

### ISSUE THREAD

**Issue by MaestroDagan** [webdev-20/TLL-hacktoberfest-2022#33]
**Task**
What is the task? Adding the possibility to write your own short link (for example with bit.lies: bit.ly/Riverz instead of bit.ly/HfDMoP).

**More about the task (optional)**
I'm only planning to add this option server-side/back-end.

**Alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by MaestroDagan** [comment]
I'm going to do this btw.

**Comment by MaestroDagan** [comment]
!assign

**Comment by MaestroDagan** [comment]
idk how to assign, if anyone knows pls tell me

**Comment by MaestroDagan** [comment]
I don't know how to add labels either

**Comment by cherylli** [comment]
i assigned you. Can you tell me how you're going to implement this feature?

**Comment by MaestroDagan** [comment]
I didn't see your message, i've already opened the PR. Sorry for my silly mistakes, i'm still pretty new to this opensource thing, but I'll explain how i implemented the feature

**Comment by MaestroDagan** [comment]
If the short property in the request body exists the value of randomString will be that, otherwise it'll be a random string.

**Comment by cherylli** [comment]
thanks I've checked your pr and requested some changes. also could you please turn off your auto format for now? we will add prettier to standardize formatting soon

**Comment by MaestroDagan** [comment]
okay, thank you! And i'll turn my auto format off

**Comment by MaestroDagan** [comment]
do you also want me to try to change all the formatting my auto formatter has done back?
