### ISSUE TITLE
feat: utils (front-end)

### ISSUE THREAD

**Issue by MaestroDagan** [webdev-20/TLL-hacktoberfest-2022#36]
**Task**
What is the task? Adding api requests in the utils folder.

**More about the task (optional)**
This will happen client-side/front-end.
I'll use Axios for this.

**Alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by MaestroDagan** [comment]
I'll start working on this today

**Comment by cherylli** [comment]
please put the api requests in the "services" folder instead.

**Comment by MaestroDagan** [comment]
okay, I'll do it in the services folder

**Comment by cherylli** [comment]
duplicate #43
