### ISSUE TITLE
Add style guide

### ISSUE THREAD

**Issue by MaestroDagan** [webdev-20/TLL-hacktoberfest-2022#38]
**Task**
What is the task? Creating and using a style guide

**More about the task (optional)**
It could contain things like when to add a newLine etc.

**Comment by klezi10** [comment]
Hi @MaestroDagan Please be aware that opening an issue doesn't mean your PR will be accepted. We have collaborators working on design so when opening an issue, it would be a good idea to wait for a maintainer to accept your issue and assign it to you before you begin your work.

**Comment by MaestroDagan** [comment]
Oh sorry, didn't knew that. I'll stop doing it.

**Comment by cherylli** [comment]
don't think we need one. have added a prettierrc file to the repo which we will all use
