### ISSUE TITLE
feat: front-end update

### ISSUE THREAD

**Issue by MaestroDagan** [webdev-20/TLL-hacktoberfest-2022#50]
**Task**
What is the task? Making the front end more like the example.

**More about the task (optional)**
Fixing background color.
Fixing URL shortening div color.
Fixing font colors.
Fixing website title.
Moving footer to bottom of page.
Adding borders.
Adding the text at the top of the page.
Adding links to the GitHub etc.

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/84450344/193662837-9f32a94a-55d3-47c4-9658-b9468ba4d398.png)
![image](https://user-images.githubusercontent.com/84450344/193663162-526fefc1-d859-47b5-98f1-4f2db6adb3cf.png)

**Comment by MaestroDagan** [comment]
Could I get assigned to this? @cherylli

**Comment by cherylli** [comment]
Sorry we already have a design team working in this and will have someone working on the styling.

**Comment by MaestroDagan** [comment]
Okay!
